### ISSUE TITLE
Add Tabbed Navigation for Getting Started

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#80]
## Problem

The _Getting Started_ guides are broken into multiple scenarios:

- OS X or Windows
- CLI or Desktop
- Android or iOS or Windows Phone

## Solution

We can either break these out into separate articles or we can provide a dynamic tabbed navigation.

I'm happy with either solution as long as it's straight-forward for the user and supports perma-linking.

**Comment by GarthDB** [comment]
The current plan is dynamic tabbed navigation, but they are separate pages with distinct urls. The downside is the page loading each time you change tabs (not always expected behavior).

**Comment by mwbrooks** [comment]
Cool, is there an implementation or plugin for this functionality or will we implement it ourselves?

**Comment by GarthDB** [comment]
Implement ourselves based on frontmatter metadata.




```yml


---

title: Step 1: Install PhoneGap Desktop

url: getting-started/1-install-phonegap/desktop

layout: subpage

tab: Desktop

—

```

**Comment by GarthDB** [comment]
Implement ourselves based on frontmatter metadata.

```yml
---
title: Step 1: Install PhoneGap Desktop
url: getting-started/1-install-phonegap/desktop
layout: subpage
tab: Desktop
—
```
